# TCL File Generated by Component Editor 11.1sp2
# Sat Mar 31 19:11:15 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | AUDIO_IF "AUDIO_IF" v2.0
# | null 2012.03.31.19:11:15
# | 
# | 
# | D:/SVN/DE2/DE2/test/SOPC_Q11_1/DE2_SD_Card_Audio/TERASIC_AUDIO/AUDIO_IF.v
# | 
# |    ./AUDIO_IF.v syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module AUDIO_IF
# | 
set_module_property DESCRIPTION ""
set_module_property NAME AUDIO_IF
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME AUDIO_IF
set_module_property TOP_LEVEL_HDL_FILE AUDIO_IF.v
set_module_property TOP_LEVEL_HDL_MODULE AUDIO_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME AUDIO_IF
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file AUDIO_IF.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset clock_sink_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avs_s1_address address Input 3
add_interface_port avalon_slave avs_s1_read read Input 1
add_interface_port avalon_slave avs_s1_readdata readdata Output 16
add_interface_port avalon_slave avs_s1_write write Input 1
add_interface_port avalon_slave avs_s1_writedata writedata Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink avs_s1_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_reset
# | 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT

set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset avs_s1_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end avs_s1_export_XCK export Output 1
add_interface_port conduit_end avs_s1_export_ADCDAT export Input 1
add_interface_port conduit_end avs_s1_export_ADCLRC export Input 1
add_interface_port conduit_end avs_s1_export_DACDAT export Output 1
add_interface_port conduit_end avs_s1_export_DACLRC export Input 1
add_interface_port conduit_end avs_s1_export_BCLK export Input 1
# | 
# +-----------------------------------
